# This is a basic workflow to help you get started with Actions

name: Scan top 10 repositories
on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch top 10 repositories
        run: |
          repos=$(curl -s "https://api.github.com/search/repositories?q=stars:>0&sort=stars&per_page=10" | jq -r '.items[] | .clone_url')
          echo "$repos"

      - name: Clone and scan repositories
        run: |
          for repo in $repos; do
            git clone "$repo"
            repo_name=$(echo "$repo" | sed 's#.*/##')
            cd "$repo_name"
            echo "Scanning $repo_name with Checkov..."
            docker run -v "$(pwd):/tmp" bridgecrew/checkov:latest -d /tmp
            echo "Scanning $repo_name with Gitleaks..."
            docker run -v "$(pwd):/tmp" zricethezav/gitleaks:latest --verbose --redact --repo-config=./.gitleaks.toml
            cd ..
          done
